language: generic

sudo: required

services: 
  - docker

before_install:
  - docker build -t hoijookim/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true hoijookim/react-test-app npm run test

after_success:
  - docker build -t hoijookim/docker-frontend ./frontend
  - docker build -t hoijookim/docker-backend ./backend
  - docker build -t hoijookim/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push hoijookim/docker-frontend
  - docker push hoijookim/docker-backend
  - docker push hoijookim/docker-nginx